USE ${dbname.mysql};

LOAD DATA LOCAL INFILE '@CSVDIR@/hibernate_sequence.csv'
INTO TABLE hibernate_sequence
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '@CSVDIR@/kunde.csv'
INTO TABLE kunde
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '@CSVDIR@/adresse.csv'
INTO TABLE adresse
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES;
--
--LOAD DATA LOCAL INFILE '@CSVDIR@/wartungsvertrag.csv'
--INTO TABLE wartungsvertrag
--FIELDS TERMINATED BY ';'
--OPTIONALLY ENCLOSED BY '"'
--IGNORE 1 LINES;
--
--LOAD DATA LOCAL INFILE '@CSVDIR@/bestellung.csv'
--INTO TABLE bestellung
--FIELDS TERMINATED BY ';'
--OPTIONALLY ENCLOSED BY '"'
--IGNORE 1 LINES;
--
--LOAD DATA LOCAL INFILE '@CSVDIR@/artikel.csv'
--INTO TABLE artikel
--FIELDS TERMINATED BY ';'
--OPTIONALLY ENCLOSED BY '"'
--IGNORE 1 LINES;
--
--LOAD DATA LOCAL INFILE '@CSVDIR@/bestellposition.csv'
--INTO TABLE bestellposition
--FIELDS TERMINATED BY ';'
--OPTIONALLY ENCLOSED BY '"'
--IGNORE 1 LINES;
--
--LOAD DATA LOCAL INFILE '@CSVDIR@/lieferung.csv'
--INTO TABLE lieferung
--FIELDS TERMINATED BY ';'
--OPTIONALLY ENCLOSED BY '"'
--IGNORE 1 LINES;
--
--LOAD DATA LOCAL INFILE '@CSVDIR@/bestellung_lieferung.csv'
--INTO TABLE bestellung_lieferung
--FIELDS TERMINATED BY ';'
--OPTIONALLY ENCLOSED BY '"'
--IGNORE 1 LINES;
